### ISSUE TITLE
restraint requires git archive to be set on git server 

### ISSUE THREAD

**Issue by mrniranjan** [p3ck/restraint#31]
restraint requires git archive to be set on git server,  for example git.fedorahosted.org/git/pki-tests.git 
$ git archive -v --remote=git://git.fedorahosted.org/git/pki.git master: -o 1.tar
fatal: The remote end hung up unexpectedly

Can this hard requirement be done with. This is hampering us from to doing upstream ci. at-least for projects hosted in git.fedoraproject.org/pki-tests/

**Comment by p3ck** [comment]
restraint now supports https archives from github.
