### ISSUE TITLE
Key file contains key 'use_pty' which has a value that cannot be interpreted.

### ISSUE THREAD

**Issue by Tiboris** [p3ck/restraint#34]
**I have tried to set metadata as shown:**

```
[General]
name=/restraint/env/metadata
owner=Tibor Dudlák <tdudlak@redhat.com>
description=test
license=GPLv3
confidential=no
destructive=no

[restraint]
entry_point=./runtest.sh
max_time=1m
dependencies=expect
use_pty=False
```

**but get this error:**
_Key file contains key 'use_pty' which has a value that cannot be interpreted._

```
** Fetching task: 46388146 [/mnt/tests/git.engineering.redhat.com/users/tdudlak/testing.git/tests]
** Extracting metadata
** Extracting runtest.sh
** Preparing metadata
** ERROR: Key file contains key 'use_pty' which has a value that cannot be interpreted.
** Completed Task : 46388146
```

I followed  http://restraint.readthedocs.io/en/latest/tasks.html#metadata 

Found out that the value of 'FALSE' (when use_pty is not set it is it's default value) is expected not 'False'.

**Comment by p3ck** [comment]
Are you sure FALSE worked for you?  False also didn't work for me but it was all lower case false that I found actually worked.

**Comment by p3ck** [comment]
fixed in upstream

**Comment by Tiboris** [comment]
Yes pretty sure with 'FALSE' and also Thank you! 👍
