### ISSUE TITLE
[RFE] more useful error logging

### ISSUE THREAD

**Issue by AloisMahdal** [p3ck/restraint#38]
Recently we ran into issue where a package installed in previous task broke yum, so restraint wasn't able to install next task, so it gave up.

Looking at harness.log:

    ** Fetching task: 95021052 [/mnt/tests/distribution/upgrade/do-leapp]
    use_pty:FALSE rstrnt-package reinstall distribution-distribution-upgrade-do-leapp
    Loaded plugins: aliases, auto-update-debuginfo, changelog, copr, fastestmirror,
                  : filter-data, fs-snapshot, kabi, keys, langpacks, list-data,
                  : local, merge-conf, ovl, post-transaction-actions, pre-
                  : transaction-actions, priorities, product-id, protectbase, ps,
                  : refresh-packagekit, remove-with-leaves, rpm-warm-cache, search-
                  : disabled-repos, show-leaves, subscription-manager, tmprepo,
                  : tsflags, upgrade-helper, verify, versionlock
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    Loading support for Red Hat kernel ABI
    No Match for argument: distribution-distribution-upgrade-do-leapp
    No Packages marked for removal
    Loaded plugins: aliases, auto-update-debuginfo, changelog, copr, fastestmirror,
                  : filter-data, fs-snapshot, kabi, keys, langpacks, list-data,
                  : local, merge-conf, ovl, post-transaction-actions, pre-
                  : transaction-actions, priorities, product-id, protectbase, ps,
                  : refresh-packagekit, remove-with-leaves, rpm-warm-cache, search-
                  : disabled-repos, show-leaves, subscription-manager, tmprepo,
                  : tsflags, upgrade-helper, verify, versionlock
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    Loading support for Red Hat kernel ABI

    You have enabled checking of packages via GPG keys. This is a good thing. 
    However, you do not have any GPG public keys installed. You need to download
    the keys for packages you wish to install and install them.
    You can do that by running the command:
        rpm --import public.gpg.key

    Alternatively you can specify the url to the key you would like to use
    for a repository in the 'gpgkey' option in a repository section and yum 
    will install it for you.

    For more information contact your distribution or package provider.

    Problem repository: _local
    Loaded plugins: aliases, auto-update-debuginfo, changelog, copr, fastestmirror,
                  : filter-data, fs-snapshot, kabi, keys, langpacks, list-data,
                  : local, merge-conf, ovl, post-transaction-actions, pre-
                  : transaction-actions, priorities, product-id, protectbase, ps,
                  : refresh-packagekit, remove-with-leaves, rpm-warm-cache, search-
                  : disabled-repos, show-leaves, subscription-manager, tmprepo,
                  : tsflags, upgrade-helper, verify, versionlock
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    Loading support for Red Hat kernel ABI

    You have enabled checking of packages via GPG keys. This is a good thing. 
    However, you do not have any GPG public keys installed. You need to download
    the keys for packages you wish to install and install them.
    You can do that by running the command:
        rpm --import public.gpg.key

    Alternatively you can specify the url to the key you would like to use
    for a repository in the 'gpgkey' option in a repository section and yum 
    will install it for you.

    For more information contact your distribution or package provider.

    Problem repository: _local
    Loaded plugins: aliases, auto-update-debuginfo, changelog, copr, fastestmirror,
                  : filter-data, fs-snapshot, kabi, keys, langpacks, list-data,
                  : local, merge-conf, ovl, post-transaction-actions, pre-
                  : transaction-actions, priorities, product-id, protectbase, ps,
                  : refresh-packagekit, remove-with-leaves, rpm-warm-cache, search-
                  : disabled-repos, show-leaves, subscription-manager, tmprepo,
                  : tsflags, upgrade-helper, verify, versionlock
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    Loading support for Red Hat kernel ABI

    You have enabled checking of packages via GPG keys. This is a good thing. 
    However, you do not have any GPG public keys installed. You need to download
    the keys for packages you wish to install and install them.
    You can do that by running the command:
        rpm --import public.gpg.key

    Alternatively you can specify the url to the key you would like to use
    for a repository in the 'gpgkey' option in a repository section and yum 
    will install it for you.

    For more information contact your distribution or package provider.

    Problem repository: _local
    Loaded plugins: aliases, auto-update-debuginfo, changelog, copr, fastestmirror,
                  : filter-data, fs-snapshot, kabi, keys, langpacks, list-data,
                  : local, merge-conf, ovl, post-transaction-actions, pre-
                  : transaction-actions, priorities, product-id, protectbase, ps,
                  : refresh-packagekit, remove-with-leaves, rpm-warm-cache, search-
                  : disabled-repos, show-leaves, subscription-manager, tmprepo,
                  : tsflags, upgrade-helper, verify, versionlock
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    Loading support for Red Hat kernel ABI

    You have enabled checking of packages via GPG keys. This is a good thing. 
    However, you do not have any GPG public keys installed. You need to download
    the keys for packages you wish to install and install them.
    You can do that by running the command:
        rpm --import public.gpg.key

    Alternatively you can specify the url to the key you would like to use
    for a repository in the 'gpgkey' option in a repository section and yum 
    will install it for you.

    For more information contact your distribution or package provider.

    Problem repository: _local
    Loaded plugins: aliases, auto-update-debuginfo, changelog, copr, fastestmirror,
                  : filter-data, fs-snapshot, kabi, keys, langpacks, list-data,
                  : local, merge-conf, ovl, post-transaction-actions, pre-
                  : transaction-actions, priorities, product-id, protectbase, ps,
                  : refresh-packagekit, remove-with-leaves, rpm-warm-cache, search-
                  : disabled-repos, show-leaves, subscription-manager, tmprepo,
                  : tsflags, upgrade-helper, verify, versionlock
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    Loading support for Red Hat kernel ABI

    You have enabled checking of packages via GPG keys. This is a good thing. 
    However, you do not have any GPG public keys installed. You need to download
    the keys for packages you wish to install and install them.
    You can do that by running the command:
        rpm --import public.gpg.key

    Alternatively you can specify the url to the key you would like to use
    for a repository in the 'gpgkey' option in a repository section and yum 
    will install it for you.

    For more information contact your distribution or package provider.

    Problem repository: _local
    ** ERROR: Command returned non-zero 256
    ** Completed Task : 95021052

..errors from yum are there, but it would help make clear:

 * which part of output belongs to restraint
 * which part belongs to the command being called,
 * what is the command that was called.

The thing that was ultimately confusing in this case is that the errors actually appeared earlier with earlier tasks, but for some reason only at this point they were considrerd fatal.  So we actually treated the errors as false alarm.  It would help if restraint made clear that this is the reason why it's quitting.

console.log output has even less details:

    [   85.143588] virbr0: port 1(virbr0-nic) entered disabled state 
    [-- MARK -- Thu Jun 20 00:15:00 2019] 
    [-- MARK -- Thu Jun 20 00:20:00 2019] 
    [  655.219209] restraintd[22644]: * Fetching recipe: http://lab-02.rhts.eng.brq.redhat.com:8000//recipes/7020907/ 
    [  656.732253] restraintd[22644]: * Parsing recipe 
    [  658.690443] restraintd[22644]: * Running recipe 
    [  658.693616] restraintd[22644]: ** Continuing task: 95021051 [/mnt/tests/distribution/upgrade/save-state] 
    [  658.897455] restraintd[22644]: ** Preparing metadata 
    [  659.489105] restraintd[22644]: ** Refreshing peer role hostnames 
    [  661.312261] restraintd[22644]: ** Updating env vars 
    [  662.948907] restraintd[22644]: ** Running task: 95021051 [/distribution/upgrade/save-state] 
    [  723.278190] restraintd[22644]: *** Current Time: Thu Jun 20 02:22:15 2019 Localwatchdog at: Thu Jun 20 02:36:15 2019 
    [  736.524124] restraintd[22644]: ** Completed Task : 95021051 
    [  737.508459] restraintd[22644]: ** Fetching task: 95021052 [/mnt/tests/distribution/upgrade/do-leapp] 
    [  851.718222] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [  851.721094] restraintd[22644]: ** Completed Task : 95021052 
    [  853.048162] restraintd[22644]: ** Fetching task: 95021053 [/mnt/tests/distribution/upgrade/check-distro] 
    [-- MARK -- Thu Jun 20 00:25:00 2019] 
    [  932.979185] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [  932.981731] restraintd[22644]: ** Completed Task : 95021053 
    [  934.015602] restraintd[22644]: ** Fetching task: 95021054 [/mnt/tests/distribution/upgrade/check-rhsm] 
    [  944.861305] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [  944.864474] restraintd[22644]: ** Completed Task : 95021054 
    [  945.793358] restraintd[22644]: ** Fetching task: 95021055 [/mnt/tests/distribution/upgrade/check-packages] 
    [  956.845305] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [  956.848121] restraintd[22644]: ** Completed Task : 95021055 
    [  957.755601] restraintd[22644]: ** Fetching task: 95021056 [/mnt/tests/distribution/upgrade/check-state] 
    [  969.072988] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [  969.075419] restraintd[22644]: ** Completed Task : 95021056 
    [  969.997801] restraintd[22644]: ** Fetching task: 95021057 [/mnt/tests/distribution/upgrade/check-yum] 
    [  983.159239] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [  983.161907] restraintd[22644]: ** Completed Task : 95021057 
    [  984.172053] restraintd[22644]: ** Fetching task: 95021058 [/mnt/tests/distribution/upgrade/test/upg/any/allpkgs] 
    [ 1012.618182] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [ 1012.620706] restraintd[22644]: ** Completed Task : 95021058 
    [ 1013.497445] restraintd[22644]: ** Fetching task: 95021059 [/mnt/tests/distribution/upgrade/unsubscribe-rhsm] 
    [ 1024.416329] restraintd[22644]: ** ERROR: Command returned non-zero 256 
    [ 1024.418884] restraintd[22644]: ** Completed Task : 95021059 
    [ 1025.382036] restraintd[22644]: * Finished recipe 
    [-- MARK -- Thu Jun 20 00:30:00 2019] 
    [-- MARK -- Thu Jun 20 00:35:00 2019] 
    [-- MARK -- Thu Jun 20 00:40:00 2019] 
    [-- MARK -- Thu Jun 20 00:45:00 2019] 
    [...]

The package was *restraint-0.1.39-1.el7bkr* on RHEL-7.6.

**Comment by StykMartin** [comment]
Hello @AloisMahdal.
Restraint is no more maintained by this repository. 
Can you please file a bug here:
https://bugzilla.redhat.com/enter_bug.cgi?product=Restraint

**Comment by AloisMahdal** [comment]
Sure, [reported](https://bugzilla.redhat.com/show_bug.cgi?id=1722566).  Thanks!
