### ISSUE TITLE
PTY needed for ausearch after 0.2.0 upgrade

### ISSUE THREAD

**Issue by The-Mule** [p3ck/restraint#40]
Beaker tasks for audit testing usually consist of adding some audit rule, generating audit event and then using ausearch to check that event was logged in audit log. Hence we usually follow this scheme in runtest.sh:

rlRun "auditctl -a ..." 0 "Add rule catching event X"
rlRun "..." 0 "Do some action o trigger event X"
rlRun "ausearch ..." 0 "Check that event X was logged"
 
Previously, with restraint 0.1.45, we were running beaker tasks for audit testing without issues. 

Now with restraint-0.2.0 all tests started failing. RHEL version is the same, audit and kernel packages are the same, the only difference is the version of restraint. All ausearch commands fail, no events are found even after 30 seconds waiting.

However, when the beaker machine is reserved and test is executed manually by running 'make run' in ssh spawned shell in the machine, all tests pass correctly (without waiting). This usually seems to indicate that (pseudo)terminal is needed. Indeed, when ausearch is executed by 'unbuffer' then tests pass in beaker too:

rlRun "unbuffer ausearch ..." 0 "Check that event X was logged"

Clearly, ausearch need some kind of tty/pty or some other IO mechanism in place to work. Since it was working in 0.1.45 there must be some change related to IO between 0.1.45 and 0.2.0. I tried to bisect commits and it seems to stop working after some of the following commits:

o Remove libssh from restraint client
o Add pkg_commands.d files for debian and ubuntu
o Replace rhts-sync cmds with rstrnt-sync-... cmds
o Remove execute permission from systemd service file

I suspect that removing libssh might be the change breaking our tests. 

Can you please help me understand what changed? Was the change intentional? Hundreds of tests are using ausearch command and it would be expensive and risky to change all of them. If we need to do it, we need to understand why.

**Comment by StykMartin** [comment]
This is not the right place for raising this issue.
Beaker team can handle this, so please raise this in [beaker-project/restraint](https://github.com/beaker-project/restraint)

**Comment by The-Mule** [comment]
Sorry, fixed - https://github.com/beaker-project/restraint/issues/24.
